// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

/**
 * Protobuf type {@code vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryResponse}
 */
public  final class HistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryResponse)
    HistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HistoryResponse.newBuilder() to construct.
  private HistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HistoryResponse() {
    id_ = 0L;
    createdOn_ = "";
    historyDetailResponse_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HistoryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            createdOn_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              historyDetailResponse_ = new java.util.ArrayList<HistoryDetailResponse>();
              mutable_bitField0_ |= 0x00000004;
            }
            historyDetailResponse_.add(
                input.readMessage(HistoryDetailResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        historyDetailResponse_ = java.util.Collections.unmodifiableList(historyDetailResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RockPaperScissors.internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RockPaperScissors.internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            HistoryResponse.class, HistoryResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int CREATEDON_FIELD_NUMBER = 2;
  private volatile Object createdOn_;
  /**
   * <code>string createdOn = 2;</code>
   */
  public String getCreatedOn() {
    Object ref = createdOn_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createdOn_ = s;
      return s;
    }
  }
  /**
   * <code>string createdOn = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedOnBytes() {
    Object ref = createdOn_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      createdOn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HISTORYDETAILRESPONSE_FIELD_NUMBER = 3;
  private java.util.List<HistoryDetailResponse> historyDetailResponse_;
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
   */
  public java.util.List<HistoryDetailResponse> getHistoryDetailResponseList() {
    return historyDetailResponse_;
  }
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
   */
  public java.util.List<? extends HistoryDetailResponseOrBuilder>
      getHistoryDetailResponseOrBuilderList() {
    return historyDetailResponse_;
  }
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
   */
  public int getHistoryDetailResponseCount() {
    return historyDetailResponse_.size();
  }
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
   */
  public HistoryDetailResponse getHistoryDetailResponse(int index) {
    return historyDetailResponse_.get(index);
  }
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
   */
  public HistoryDetailResponseOrBuilder getHistoryDetailResponseOrBuilder(
      int index) {
    return historyDetailResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getCreatedOnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, createdOn_);
    }
    for (int i = 0; i < historyDetailResponse_.size(); i++) {
      output.writeMessage(3, historyDetailResponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getCreatedOnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, createdOn_);
    }
    for (int i = 0; i < historyDetailResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, historyDetailResponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof HistoryResponse)) {
      return super.equals(obj);
    }
    HistoryResponse other = (HistoryResponse) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getCreatedOn()
        .equals(other.getCreatedOn());
    result = result && getHistoryDetailResponseList()
        .equals(other.getHistoryDetailResponseList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + CREATEDON_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedOn().hashCode();
    if (getHistoryDetailResponseCount() > 0) {
      hash = (37 * hash) + HISTORYDETAILRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getHistoryDetailResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static HistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static HistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static HistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static HistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(HistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryResponse)
      HistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RockPaperScissors.internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RockPaperScissors.internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HistoryResponse.class, HistoryResponse.Builder.class);
    }

    // Construct using vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHistoryDetailResponseFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      createdOn_ = "";

      if (historyDetailResponseBuilder_ == null) {
        historyDetailResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        historyDetailResponseBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RockPaperScissors.internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_descriptor;
    }

    public HistoryResponse getDefaultInstanceForType() {
      return HistoryResponse.getDefaultInstance();
    }

    public HistoryResponse build() {
      HistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public HistoryResponse buildPartial() {
      HistoryResponse result = new HistoryResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.createdOn_ = createdOn_;
      if (historyDetailResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          historyDetailResponse_ = java.util.Collections.unmodifiableList(historyDetailResponse_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.historyDetailResponse_ = historyDetailResponse_;
      } else {
        result.historyDetailResponse_ = historyDetailResponseBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof HistoryResponse) {
        return mergeFrom((HistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(HistoryResponse other) {
      if (other == HistoryResponse.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getCreatedOn().isEmpty()) {
        createdOn_ = other.createdOn_;
        onChanged();
      }
      if (historyDetailResponseBuilder_ == null) {
        if (!other.historyDetailResponse_.isEmpty()) {
          if (historyDetailResponse_.isEmpty()) {
            historyDetailResponse_ = other.historyDetailResponse_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureHistoryDetailResponseIsMutable();
            historyDetailResponse_.addAll(other.historyDetailResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.historyDetailResponse_.isEmpty()) {
          if (historyDetailResponseBuilder_.isEmpty()) {
            historyDetailResponseBuilder_.dispose();
            historyDetailResponseBuilder_ = null;
            historyDetailResponse_ = other.historyDetailResponse_;
            bitField0_ = (bitField0_ & ~0x00000004);
            historyDetailResponseBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHistoryDetailResponseFieldBuilder() : null;
          } else {
            historyDetailResponseBuilder_.addAllMessages(other.historyDetailResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      HistoryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (HistoryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {

      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {

      id_ = 0L;
      onChanged();
      return this;
    }

    private Object createdOn_ = "";
    /**
     * <code>string createdOn = 2;</code>
     */
    public String getCreatedOn() {
      Object ref = createdOn_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createdOn_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string createdOn = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedOnBytes() {
      Object ref = createdOn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createdOn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string createdOn = 2;</code>
     */
    public Builder setCreatedOn(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      createdOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string createdOn = 2;</code>
     */
    public Builder clearCreatedOn() {

      createdOn_ = getDefaultInstance().getCreatedOn();
      onChanged();
      return this;
    }
    /**
     * <code>string createdOn = 2;</code>
     */
    public Builder setCreatedOnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      createdOn_ = value;
      onChanged();
      return this;
    }

    private java.util.List<HistoryDetailResponse> historyDetailResponse_ =
      java.util.Collections.emptyList();
    private void ensureHistoryDetailResponseIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        historyDetailResponse_ = new java.util.ArrayList<HistoryDetailResponse>(historyDetailResponse_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        HistoryDetailResponse, HistoryDetailResponse.Builder, HistoryDetailResponseOrBuilder> historyDetailResponseBuilder_;

    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public java.util.List<HistoryDetailResponse> getHistoryDetailResponseList() {
      if (historyDetailResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(historyDetailResponse_);
      } else {
        return historyDetailResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public int getHistoryDetailResponseCount() {
      if (historyDetailResponseBuilder_ == null) {
        return historyDetailResponse_.size();
      } else {
        return historyDetailResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public HistoryDetailResponse getHistoryDetailResponse(int index) {
      if (historyDetailResponseBuilder_ == null) {
        return historyDetailResponse_.get(index);
      } else {
        return historyDetailResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder setHistoryDetailResponse(
        int index, HistoryDetailResponse value) {
      if (historyDetailResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryDetailResponseIsMutable();
        historyDetailResponse_.set(index, value);
        onChanged();
      } else {
        historyDetailResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder setHistoryDetailResponse(
        int index, HistoryDetailResponse.Builder builderForValue) {
      if (historyDetailResponseBuilder_ == null) {
        ensureHistoryDetailResponseIsMutable();
        historyDetailResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        historyDetailResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder addHistoryDetailResponse(HistoryDetailResponse value) {
      if (historyDetailResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryDetailResponseIsMutable();
        historyDetailResponse_.add(value);
        onChanged();
      } else {
        historyDetailResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder addHistoryDetailResponse(
        int index, HistoryDetailResponse value) {
      if (historyDetailResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryDetailResponseIsMutable();
        historyDetailResponse_.add(index, value);
        onChanged();
      } else {
        historyDetailResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder addHistoryDetailResponse(
        HistoryDetailResponse.Builder builderForValue) {
      if (historyDetailResponseBuilder_ == null) {
        ensureHistoryDetailResponseIsMutable();
        historyDetailResponse_.add(builderForValue.build());
        onChanged();
      } else {
        historyDetailResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder addHistoryDetailResponse(
        int index, HistoryDetailResponse.Builder builderForValue) {
      if (historyDetailResponseBuilder_ == null) {
        ensureHistoryDetailResponseIsMutable();
        historyDetailResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        historyDetailResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder addAllHistoryDetailResponse(
        Iterable<? extends HistoryDetailResponse> values) {
      if (historyDetailResponseBuilder_ == null) {
        ensureHistoryDetailResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, historyDetailResponse_);
        onChanged();
      } else {
        historyDetailResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder clearHistoryDetailResponse() {
      if (historyDetailResponseBuilder_ == null) {
        historyDetailResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        historyDetailResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public Builder removeHistoryDetailResponse(int index) {
      if (historyDetailResponseBuilder_ == null) {
        ensureHistoryDetailResponseIsMutable();
        historyDetailResponse_.remove(index);
        onChanged();
      } else {
        historyDetailResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public HistoryDetailResponse.Builder getHistoryDetailResponseBuilder(
        int index) {
      return getHistoryDetailResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public HistoryDetailResponseOrBuilder getHistoryDetailResponseOrBuilder(
        int index) {
      if (historyDetailResponseBuilder_ == null) {
        return historyDetailResponse_.get(index);  } else {
        return historyDetailResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public java.util.List<? extends HistoryDetailResponseOrBuilder>
         getHistoryDetailResponseOrBuilderList() {
      if (historyDetailResponseBuilder_ != null) {
        return historyDetailResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(historyDetailResponse_);
      }
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public HistoryDetailResponse.Builder addHistoryDetailResponseBuilder() {
      return getHistoryDetailResponseFieldBuilder().addBuilder(
          HistoryDetailResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public HistoryDetailResponse.Builder addHistoryDetailResponseBuilder(
        int index) {
      return getHistoryDetailResponseFieldBuilder().addBuilder(
          index, HistoryDetailResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryDetailResponse historyDetailResponse = 3;</code>
     */
    public java.util.List<HistoryDetailResponse.Builder>
         getHistoryDetailResponseBuilderList() {
      return getHistoryDetailResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        HistoryDetailResponse, HistoryDetailResponse.Builder, HistoryDetailResponseOrBuilder>
        getHistoryDetailResponseFieldBuilder() {
      if (historyDetailResponseBuilder_ == null) {
        historyDetailResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            HistoryDetailResponse, HistoryDetailResponse.Builder, HistoryDetailResponseOrBuilder>(
                historyDetailResponse_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        historyDetailResponse_ = null;
      }
      return historyDetailResponseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.HistoryResponse)
  private static final HistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HistoryResponse();
  }

  public static HistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<HistoryResponse>() {
    public HistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HistoryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HistoryResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<HistoryResponse> getParserForType() {
    return PARSER;
  }

  public HistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

