// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public interface PlayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.PlayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int32 type = 2;</code>
   */
  int getType();
}
