// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public final class RockPaperScissors {
  private RockPaperScissors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031rock-paper-scissors.proto\0222vn.zalopay." +
      "gitlab.phuctt4.rock.paper.scissors.grpc\"" +
      "\020\n\016SessionRequest\"\035\n\017SessionResponse\022\n\n\002" +
      "id\030\001 \001(\0032\253\001\n\016SessionService\022\230\001\n\rcreateSe" +
      "ssion\022B.vn.zalopay.gitlab.phuctt4.rock.p" +
      "aper.scissors.grpc.SessionRequest\032C.vn.z" +
      "alopay.gitlab.phuctt4.rock.paper.scissor" +
      "s.grpc.SessionResponseB\005P\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor,
        new String[] { });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor,
        new String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
