// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public final class RockPaperScissors {
  private RockPaperScissors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031rock-paper-scissors.proto\0222vn.zalopay." +
      "gitlab.phuctt4.rock.paper.scissors.grpc\"" +
      "\037\n\016SessionRequest\022\r\n\005turns\030\001 \001(\005\",\n\017Sess" +
      "ionResponse\022\n\n\002id\030\001 \001(\003\022\r\n\005turns\030\002 \001(\0052\253" +
      "\001\n\016SessionService\022\230\001\n\rcreateService\022B.vn" +
      ".zalopay.gitlab.phuctt4.rock.paper.sciss" +
      "ors.grpc.SessionRequest\032C.vn.zalopay.git" +
      "lab.phuctt4.rock.paper.scissors.grpc.Ses" +
      "sionResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor,
        new String[] { "Turns", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor,
        new String[] { "Id", "Turns", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
