// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public final class RockPaperScissors {
  private RockPaperScissors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031rock-paper-scissors.proto\0222vn.zalopay." +
      "gitlab.phuctt4.rock.paper.scissors.grpc\"" +
      "\020\n\016SessionRequest\"\035\n\017SessionResponse\022\n\n\002" +
      "id\030\001 \001(\003\"1\n\013UserRequest\022\020\n\010username\030\001 \001(" +
      "\t\022\020\n\010password\030\002 \001(\t\"\035\n\014UserResponse\022\r\n\005t" +
      "oken\030\001 \001(\t\"\020\n\016HistoryRequest\"5\n\025HistoryD" +
      "etailResponse\022\014\n\004type\030\001 \001(\005\022\016\n\006result\030\002 " +
      "\001(\005\"\236\001\n\023HistoryDataResponse\022\n\n\002id\030\001 \001(\003\022" +
      "\021\n\tcreatedOn\030\002 \001(\t\022h\n\025historyDetailRespo" +
      "nse\030\003 \003(\0132I.vn.zalopay.gitlab.phuctt4.ro" +
      "ck.paper.scissors.grpc.HistoryDetailResp" +
      "onse\"h\n\017HistoryResponse\022U\n\004data\030\001 \003(\0132G." +
      "vn.zalopay.gitlab.phuctt4.rock.paper.sci" +
      "ssors.grpc.HistoryDataResponse\"\'\n\013PlayRe" +
      "quest\022\n\n\002id\030\001 \001(\003\022\014\n\004type\030\002 \001(\005\"\036\n\014PlayR" +
      "esponse\022\016\n\006result\030\001 \001(\t\"\033\n\nTopRequest\022\r\n" +
      "\005limit\030\001 \001(\005\"1\n\017TopDataResponse\022\020\n\010usern" +
      "ame\030\001 \001(\t\022\014\n\004rate\030\002 \001(\001\"`\n\013TopResponse\022Q" +
      "\n\004data\030\001 \003(\0132C.vn.zalopay.gitlab.phuctt4" +
      ".rock.paper.scissors.grpc.TopDataRespons" +
      "e2\343\004\n\016SessionService\022\230\001\n\rcreateSession\022B" +
      ".vn.zalopay.gitlab.phuctt4.rock.paper.sc" +
      "issors.grpc.SessionRequest\032C.vn.zalopay." +
      "gitlab.phuctt4.rock.paper.scissors.grpc." +
      "SessionResponse\022\230\001\n\rgetAllHistory\022B.vn.z" +
      "alopay.gitlab.phuctt4.rock.paper.scissor" +
      "s.grpc.HistoryRequest\032C.vn.zalopay.gitla" +
      "b.phuctt4.rock.paper.scissors.grpc.Histo" +
      "ryResponse\022\216\001\n\013getTopLimit\022>.vn.zalopay." +
      "gitlab.phuctt4.rock.paper.scissors.grpc." +
      "TopRequest\032?.vn.zalopay.gitlab.phuctt4.r" +
      "ock.paper.scissors.grpc.TopResponse\022\211\001\n\004" +
      "play\022?.vn.zalopay.gitlab.phuctt4.rock.pa" +
      "per.scissors.grpc.PlayRequest\032@.vn.zalop" +
      "ay.gitlab.phuctt4.rock.paper.scissors.gr" +
      "pc.PlayResponse2\241\001\n\017RegisterService\022\215\001\n\010" +
      "register\022?.vn.zalopay.gitlab.phuctt4.roc" +
      "k.paper.scissors.grpc.UserRequest\032@.vn.z" +
      "alopay.gitlab.phuctt4.rock.paper.scissor" +
      "s.grpc.UserResponse2\231\001\n\013AuthService\022\211\001\n\004" +
      "auth\022?.vn.zalopay.gitlab.phuctt4.rock.pa" +
      "per.scissors.grpc.UserRequest\032@.vn.zalop" +
      "ay.gitlab.phuctt4.rock.paper.scissors.gr" +
      "pc.UserResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionRequest_descriptor,
        new String[] { });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_SessionResponse_descriptor,
        new String[] { "Id", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserRequest_descriptor,
        new String[] { "Username", "Password", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_UserResponse_descriptor,
        new String[] { "Token", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryRequest_descriptor,
        new String[] { });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDetailResponse_descriptor,
        new String[] { "Type", "Result", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryDataResponse_descriptor,
        new String[] { "Id", "CreatedOn", "HistoryDetailResponse", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_HistoryResponse_descriptor,
        new String[] { "Data", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayRequest_descriptor,
        new String[] { "Id", "Type", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_PlayResponse_descriptor,
        new String[] { "Result", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopRequest_descriptor,
        new String[] { "Limit", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopDataResponse_descriptor,
        new String[] { "Username", "Rate", });
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vn_zalopay_gitlab_phuctt4_rock_paper_scissors_grpc_TopResponse_descriptor,
        new String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
