// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public interface SessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.SessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
