// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public interface SessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.SessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 turns = 1;</code>
   */
  int getTurns();
}
