// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public interface TopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.TopRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 limit = 1;</code>
   */
  int getLimit();
}
