// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rock-paper-scissors.proto

package vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc;

public interface TopResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.TopResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.TopDataResponse data = 1;</code>
   */
  java.util.List<TopDataResponse>
      getDataList();
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.TopDataResponse data = 1;</code>
   */
  TopDataResponse getData(int index);
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.TopDataResponse data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.TopDataResponse data = 1;</code>
   */
  java.util.List<? extends TopDataResponseOrBuilder>
      getDataOrBuilderList();
  /**
   * <code>repeated .vn.zalopay.gitlab.phuctt4.rock.paper.scissors.grpc.TopDataResponse data = 1;</code>
   */
  TopDataResponseOrBuilder getDataOrBuilder(
          int index);
}
